version: '3.8'

services:
  front:
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - back

  back:
    build: ./back
    ports:
      - 3001:3001
    environment:
      DATABASE_URL: mongodb://mongo:27017/mydb
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    