version: '3.8'
services:
  front:
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
    env_file:
      - .env
    depends_on:
      - back
  back:
    build: ./back
    ports:
      - 3001:3001
    env_file:
      - .env
    volumes:
      - ./back:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env

volumes:
  mongodb_data:
